// Source of truth for the supplier questionnaire fields in this section.
// Edit this file (not data/supply-chain-questionnaire.json) and run
// `bun run build:json` to regenerate the published JSON artefact.

import type { SupplierField } from "../schema";

export const profileFields: SupplierField[] = [
  {
    id: "legalName",
    section: "profile",
    type: "string",
    label: { en: "Legal name", de: "Firmierung (Rechtsname)" },
    description: {
      en: "Required by CIR 2024/2690 §5.2(a) — supplier register entry.",
      de: "Erforderlich nach CIR 2024/2690 §5.2(a) — Lieferantenregister-Eintrag.",
    },
    legalBasis: "ENISA TIG §5.2",
    required: true,
  },
  {
    id: "registeredAddress",
    section: "profile",
    type: "string",
    label: { en: "Registered address", de: "Geschäftsanschrift" },
    description: {
      en: "Required by CIR 2024/2690 §5.2(a) — supplier register entry.",
      de: "Erforderlich nach CIR 2024/2690 §5.2(a) — Lieferantenregister-Eintrag.",
    },
    legalBasis: "ENISA TIG §5.2",
    required: true,
  },
  {
    id: "country",
    section: "profile",
    type: "country",
    label: { en: "Country", de: "Land" },
    description: {
      en: "ISO 3166-1 alpha-2 code, e.g. DE, FR, IT.",
      de: "ISO 3166-1 Alpha-2-Code, z. B. DE, FR, IT.",
    },
    legalBasis: "ENISA TIG §5.2",
    required: true,
  },
  {
    id: "primaryDomain",
    section: "profile",
    type: "url",
    label: { en: "Primary domain", de: "Primäre Domain" },
    description: {
      en: "The supplier's primary public domain.",
      de: "Die primäre öffentliche Domain des Lieferanten.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: false,
  },
  {
    id: "tagline",
    section: "profile",
    type: "string",
    label: { en: "Tagline (one line, customer-facing)", de: "Slogan (eine Zeile, kundenseitig sichtbar)" },
    description: { en: "Short summary shown to customers.", de: "Kurze Beschreibung für Kunden." },
    legalBasis: "ENISA TIG §5.2(b)",
    required: false,
  },
  {
    id: "description",
    section: "profile",
    type: "text",
    label: { en: "Public description (longer)", de: "Öffentliche Beschreibung (länger)" },
    description: { en: "Longer description of the supplier.", de: "Längere Beschreibung des Lieferanten." },
    legalBasis: "ENISA TIG §5.2(b)",
    required: false,
  },
  {
    id: "serviceDescription",
    section: "profile",
    type: "text",
    label: { en: "Description of services provided", de: "Beschreibung der erbrachten Leistungen" },
    description: {
      en: "Required by ENISA TIG §5.2(b) + §5.1.4 TIPS — clear and complete description of the ICT products and services you provide. One paragraph.",
      de: "Erforderlich nach ENISA TIG §5.2(b) + §5.1.4 TIPS — klare und vollständige Beschreibung der angebotenen IKT-Produkte und -Dienstleistungen. Ein Absatz.",
    },
    legalBasis: "ENISA TIG §5.2(b) + §5.1.4 TIPS",
    required: true,
  },
  {
    id: "dataProcessingLocations",
    section: "profile",
    type: "string",
    label: { en: "Countries / regions where customer data is processed", de: "Länder / Regionen, in denen Kundendaten verarbeitet werden" },
    description: {
      en: "Required by ENISA TIG §5.1.4 TIPS — list every country / region where your customers' data is produced, processed or stored. Comma-separated.",
      de: "Erforderlich nach ENISA TIG §5.1.4 TIPS — alle Länder / Regionen auflisten, in denen Kundendaten erstellt, verarbeitet oder gespeichert werden. Komma-getrennt.",
    },
    legalBasis: "ENISA TIG §5.1.4 TIPS",
    required: true,
  },
  {
    id: "securityContactName",
    section: "profile",
    type: "string",
    label: { en: "Security contact name", de: "Name des Sicherheitskontakts" },
    description: {
      en: "Required by CIR 2024/2690 §5.1.4(d) — incident notification chain.",
      de: "Erforderlich nach CIR 2024/2690 §5.1.4(d) — Meldekette für Sicherheitsvorfälle.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(d)",
    required: true,
  },
  {
    id: "incidentContactEmail",
    section: "profile",
    type: "email",
    label: { en: "Incident contact email", de: "E-Mail für Vorfälle" },
    description: {
      en: "Default email used by customers for incident notifications.",
      de: "Standard-E-Mail für Vorfallsmeldungen durch Kunden.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(d)",
    required: true,
  },
  {
    id: "incidentContactPhone",
    section: "profile",
    type: "phone",
    label: { en: "Incident contact phone (24/7)", de: "Telefonnummer für Vorfälle (24/7)" },
    description: {
      en: "24/7 phone for critical incident notifications.",
      de: "24/7-Telefon für kritische Vorfallsmeldungen.",
    },
    legalBasis: "CIR 2024/2690 §5.1.4(d)",
    required: false,
  },
  {
    id: "incidentSlaHours",
    section: "profile",
    type: "integer",
    label: { en: "Incident notification SLA (hours)", de: "Meldefrist für Vorfälle (Stunden)" },
    description: {
      en: "Maximum time from incident detection to customer notification.",
      de: "Maximale Zeit von Vorfallserkennung bis Kundenbenachrichtigung.",
    },
    legalBasis: "NIS2 Art. 23",
    required: false,
  },
  {
    id: "bsiRegistrationId",
    section: "profile",
    type: "string",
    label: { en: "BSI registration ID (only if your company is itself NIS2-regulated)", de: "BSI-Registrierungs-ID (nur falls Ihr Unternehmen selbst NIS2-reguliert ist)" },
    description: {
      en: "Optional. ENISA TIG §5.1.2 — if your company is itself a NIS2-regulated entity with a BSI registration, your customers can use this fact to satisfy their §5.1.2 supplier-selection criteria.",
      de: "Optional. ENISA TIG §5.1.2 — falls Ihr Unternehmen selbst NIS2-reguliert mit BSI-Registrierung ist, können Ihre Kunden diese Tatsache zur Erfüllung ihrer §5.1.2 Lieferantenauswahlkriterien nutzen.",
    },
    legalBasis: "ENISA TIG §5.1.2",
    required: false,
  },
  {
    id: "isSaas",
    section: "profile",
    type: "boolean",
    label: { en: "We provide SaaS / hosted services", de: "Wir bieten SaaS / gehostete Dienste" },
    description: {
      en: "Determines which technical questions you'll see next. Pick all that apply.",
      de: "Bestimmt, welche technischen Fragen als Nächstes erscheinen. Mehrfachauswahl möglich.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "isOnPrem",
    section: "profile",
    type: "boolean",
    label: { en: "We deliver on-prem software", de: "Wir liefern On-Prem-Software" },
    description: {
      en: "Software your customers install on their own hardware.",
      de: "Software, die Ihre Kunden auf eigener Hardware betreiben.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "isProfessionalServices",
    section: "profile",
    type: "boolean",
    label: { en: "We provide professional services / consulting", de: "Wir bieten Dienstleistungen / Beratung" },
    description: {
      en: "Consulting, implementation, training, audit work.",
      de: "Beratung, Implementierung, Schulung, Audit-Tätigkeiten.",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
  {
    id: "isManagedService",
    section: "profile",
    type: "boolean",
    label: { en: "We provide managed services / MSP", de: "Wir bieten Managed Services / MSP" },
    description: {
      en: "Operating the customer's IT under contract (MSP, MSSP).",
      de: "Betrieb der Kunden-IT im Auftrag (MSP, MSSP).",
    },
    legalBasis: "ENISA TIG §5.2(b)",
    required: true,
  },
];
